# Generated by Django 6.0.6 on 2026-06-09 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clouduser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='clouduser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Признак администратора'),
        ),
        migrations.AlterField(
            model_name='clouduser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clouduser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clouduser',
            name='nickname',
            field=models.CharField(max_length=15, verbose_name='Короткое имя'),
        ),
        migrations.AlterField(
            model_name='clouduser',
            name='storage_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Путь к хранилищу'),
        ),
        migrations.AlterField(
            model_name='clouduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_profile', to=settings.AUTH_USER_MODEL, verbose_name='Системный пользователь'),
        ),
        migrations.AlterField(
            model_name='file',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
